#-------------------------------
# General Site Settings

title: NMIT | Lars' Class Blogs
description: The Class Blog for all of my courses at NMIT. Specific course resources are in the separate pages. # this means to ignore newlines until "baseurl:"
baseurl: "/docs" # the subpath of your site, e.g. /blog
url: "https://larsoliverdam.github.io" # the base hostname & protocol for your site, e.g. http://example.com
remote_theme: artemsheludko/galada


#-------------------------------
# About Section
author-name:   Lars Oliver Dam
author-avatar: 09.jpg


#-------------------------------
# Contact links
facebook:  https://facebook.com/ # Add your Facebook handle
twitter:   https://twitter.com/ # Add your Facebook handle
instagram: https://www.instagram.com/ # Add your Facebook handle
pinterest: https://www.pinterest.com/ # Add your Facebook handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: https-larsoliverdam-github-io-docs # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: true # To enable the instafeed, use the value true. To turn off use the value false.


#-------------------------------
# Google Analytics
google-analytics: UA-157880170-1


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e


#-------------------------------
# Build settings
markdown: kramdown
permalink: ':title/'
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

paginate: 7
paginate_path: "/page/:num"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
